#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        >&2 echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        >&2 echo "Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
        exit 1
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
if [ "$ID" = "" ]; then
    ID=`id -u`
fi

if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "unlimited" ] ; then
            MAX_FD=8192
        fi
        ulimit -n $MAX_FD
    else
        >&2 echo "Could not query maximum file descriptor limit: $MAX_FD"
    fi
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# For Cygwin or MSYS, ensure paths are in UNIX format before anything is touched.
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  * )
    ;;
esac

if [ -n "$JAVA_HOME" ] ; then
    if [ -n "$MSYS2_ARG_CONV_EXCL" ] ; then
        if [ "$MSYS2_ARG_CONV_EXCL" != "*" ] ; then
            export MSYS2_ARG_CONV_EXCL="$MSYS2_ARG_CONV_EXCL;*"
        fi
    else
        export MSYS2_ARG_CONV_EXCL='*'
    fi
fi

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=gradlew" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
